name : Push and build

on : 
    push : 
        branches : main
    
    workflow_dispatch:

jobs : 
    build : 
        runs-on : ubuntu-latest

        strategy : 
            matrix : 
                node-version : [18, 20, 22]

        steps :

            - uses : actions/checkout@v4

            - name : setup node
              uses : actions/setup-node@v3
              with : 
                  node-version : ${{ matrix.node-version}}
            
            - name : install npm packages
              run : npm install

            - name : build project
              run : npm run build 

            